### ISSUE TITLE
Proposal: Application Connector Client Library

### ISSUE THREAD

**Issue by kavyakat** [kyma-incubator/hydroform#102]
**Description**

The aim here is to provide a library as a part of hydroform for integration of the Application Connector (AC) with third-party applications. Currently, such applications have to make their own implementations in order to integrate AC into their code. Providing a library to perform basic functions would make it easier for the AC to be integrated.

We also plan on providing a generic platform where the applications can use multiple types of storage solutions as per their convenience.

**Reasons**

- As of now, we do not provide code to help third-party applications integrate the Application Connector and use it for Events/API calls. Instead, it is up to the application developers to use the Kubernetes CLI to establish a secure connection, register the service/API as well as sending events using the Application Connector, which in turn trigger lambda functions.

Using the CLI here can be a cumbersome process with a lot of steps involved. For instance, for establishing a secure connection, the client needs to have a valid client certificate. In order to obtain this certificate, currently, the following steps are required:

- Get CSR info / config details from Kyma - 

		curl {CONFIGURATION_URL_WITH_TOKEN}
	^ returns csr signing url with token, subject

- Use subject to generate CSR and send it to Kyma as a post request
	^ response contains client certificate (base64 encoded)

Instead of having the third party developers do the above steps, we can, instead, provide a method in our library which takes the configuration URL as an input parameter, generate and then return the valid encoded certificate to the client. 

- Another issue that comes up is that currently, we use files for storing details such as client certificates, configurations etc. Instead, it would be better to provide users the options to use whichever storage solutions they prefer. This would help cloud based services, for instance, which prefer to not use file systems.

**Attachments**

Our library can implement some basic functions such as the following:

- connect() - Called by the application to establish a secure connection to the Kyma AC. This can generate/check for validity of certificates, establish a connection and return a valid certificate.

- createService() -  Can register a service of a third-party solution in Kyma. This service could include events/APIs.

- updateService() - Updates an already registered service by the service ID.

- sendEvent() - Used by the service (which is registered) to send an event, which can, in turn, trigger subscribed lambda functions.

- getSubscribedEvents() - Returns a list of all active events for the application. This can be useful to make sure that we're not sending notifications regarding inactive events.

- renewCertificate()

- revokeCertificate()

**Comment by kavyakat** [comment]
@a-thaler @joek Can you review this proposal?

**Comment by pbochynski** [comment]
We are going to remove the Application Connector and Application Registry from Kyma runtime. The application connectivity is now part of [compass](https://github.com/kyma-incubator/compass) project and the client library should be created there. We also plan to have a possibility to have a simpler setup for application connectivity that doesn't require certificates for local development and testing. If you still want to work on such a library, please create an issue/PR in the compass repository.
