### ISSUE TITLE
parallel-installation lib logs improvement

### ISSUE THREAD

**Issue by strekm** [kyma-incubator/hydroform#161]
**Description**

As a developer / user i want to have clean meaningful logs per default and verbose logs for debugging / troubleshooting. 

**Reasons**

AC:
- clean, meaningful logs
- configuration for enabling verbose logs 

**Attachments**

**Comment by tobiscr** [comment]
Hi Magda, is this ticket still relevant? Isn't it already covered by simply providing a proper log-function to Hydroform (like we do it in the example script: https://github.com/kyma-incubator/hydroform/blob/master/parallel-install/example/example.go#L57)
