### ISSUE TITLE
New installation: API field to toggle atomic upgrades

### ISSUE THREAD

**Issue by clebs** [kyma-incubator/hydroform#195]
**Description**

In a normal upgrade, if components can't be upgraded, the installation library will rollback. This can be problematic in non-productive clusters if we wish to debug the issues.

Add a field to the parallel install API to disable upgrade rollbacks.

**Reasons**

Allow better debugging capabilities, rollbacks need to be disabled on demand.

**Comment by tobiscr** [comment]
Atomic field was added in #198 - is this ticket also including the changes we need on the HELM client side?

**Comment by clebs** [comment]
Yes, this ticket includes 2 things:
- API change so that the CLI can send the atomic field (you already did that on the CLI ticket linked above).
- Implementation on the helm client to actually disable the rollbacks on failure.

**Comment by tobiscr** [comment]
Closing this issue as PR was merged.
