### ISSUE TITLE
New Installation: Domain resolution strategy

### ISSUE THREAD

**Issue by clebs** [kyma-incubator/hydroform#200]
**Description**

Depending on the kind of cluster, domain resolution may differ from the standard defined behaviour (user defined > provider defined > default).

The different cases need to be defined in detail and implemented in Hydroform.

The identified cases are:
- K3s: user defined > default
- Gardener: provider defined (gardener completely ignores user defined domain even if specified).
- GKE evaluation: user defined > provider defined. No DNS registration will be done and user needs to take care of it.

**Reasons**

Different cloud providers and plans require distinct domain resolution strategies.

**Comment by strekm** [comment]
will be continued on https://github.tools.sap/kyma/backlog/issues/1327
