### ISSUE TITLE
Unable to access cluster with credentials fetched from Hydroform

### ISSUE THREAD

**Issue by Szymongib** [kyma-incubator/hydroform#26]
**Description**

Kubeconfig fetched for provisioned GCP cluster, does not allow access to the cluster. Connection to cluster failes with the following error message:
```
error: cannot construct google default token source: google: could not find default credentials.
```

**Expected result**

Fetched Kubeconfig is sufficient to access the cluster.

**Actual result**

**Steps to reproduce**

- Provision the GCP cluster
- Fetch kubeconfig
- Save it to file
- export KUBECONFIG={created_file}
- run: `kubectl get pods`

**Troubleshooting**

**Comment by clebs** [comment]
Hi @Szymongib,
I had this problem too and it means you are not logged into gcloud on your terminal and thus the kubeconfig fails to obtain a token to access GCP.

Can you try running `gcloud auth application-default login` and try again?
Thanks!

**Comment by suleymanakbas91** [comment]
You need to export the env variable `GOOGLE_APPLICATION_CREDENTIALS` pointing to the credentials file you used to provision the cluster. We should document this..

**Comment by Szymongib** [comment]
Hi @clebs and @suleymanakbas91,
I've expected that the `KUBECONFIG` I download is enough to access the cluster, without having the GCP credentials.
Are my assumptions wrong? I guess if I have the credentials I do not need the `kubeconfig` at all.

**Comment by clebs** [comment]
Hi @Szymongib,

yes, that assumption is unfortuantely wrong. GCP uses token based authentication on kubeconfigs and those tokens need to be refreshed every hour. It is not possible to provide a kubeconfig that can access any GCP cluster without being authenticated in gcloud.

**Comment by suleymanakbas91** [comment]
The usage is now documented in the example: https://github.com/kyma-incubator/hydroform/tree/master/examples/gcp#run-the-example

**Comment by clebs** [comment]
Reopened to investigate a way to provide a kubeconfig that already contains a token after provisioning.
Possible solutions to investigate are:
- Terraform could be able to provide a token from the used service account to create the cluster as a return value (outputs) in the terraform state.
- It might be possible to inline the service key on the kubernetes go client when creating an API client.

**Comment by a-thaler** [comment]
Not a priority anymore
