### ISSUE TITLE
Provisioning fails with "open /app/.../terraform.tfstate: no such file or directory" error

### ISSUE THREAD

**Issue by akgalwas** [kyma-incubator/hydroform#61]
**Description**

While performing tests on Compass Provisioner component (Gardener on Azure, Gardener on GCP) I noticed the following error returned from Hydroform: "open /app/.hydroform/clusters/gardener/.../terraform.tfstate: no such file or directory" occurring once in a while (3 out of 12 runs on Azure, 1 out of 5 runs on GCP). The error occurs when provisioning Azure clusters with Gardener. After checking Gardener project it turned out that cluster has been provisioned so that the state stored by Provisioner is inconsistent.

**Expected result**

Provision method should properly manage terraform state file.  

**Actual result**

Provision method fails with error but Gardener keeps retrying cluster creation.

**Steps to reproduce**

The issue is random. The following setting were used for provisioning on Azure:
```
"clusterConfig": {
                    "name": "<name>",
                    "projectName": "<project_name>",
                    "kubernetesVersion": "1.15.4",
                    "nodeCount": 3,
                    "volumeSizeGB": 35,
                    "machineType": "Standard_D2_v3",
                    "region": "westeurope",
                    "provider": "azure",
                    "seed": "az-eu1",
                    "targetSecret": "<target secret>",
                    "diskType": "Standard_LRS",
                    "workerCidr": "10.250.0.0/19",
                    "autoScalerMin": 2,
                    "autoScalerMax": 4,
                    "maxSurge": 4,
                    "maxUnavailable": 1,
                    "providerSpecificConfig": {
                        "vnetCidr": "10.250.0.0/19"
                    }
                }
```
The following settings were used for provisioning on GCP:
```
gardenerConfig: {
          name: "<name>" 
          projectName: "<project name>" 
          kubernetesVersion: "1.15.4"
          diskType: "pd-standard"
          volumeSizeGB: 30
          nodeCount: 3
          machineType: "n1-standard-4"
          region: "europe-west4"
          provider: "gcp"
          seed: "gcp-eu1"
          targetSecret: "<target secret>"
          workerCidr: "10.250.0.0/19"
          autoScalerMin: 2
          autoScalerMax: 4
          maxSurge: 4
          maxUnavailable: 1
          providerSpecificConfig: { gcpConfig: { zone: "europe-west4-a" } }
        }
      }
```

**Comment by a-thaler** [comment]
Please verify if error occurs after fixing of https://github.com/kyma-incubator/compass/issues/823. Till then we will close the ticket. If it still occurs please re-open and provide more details
