### ISSUE TITLE
Hydroform creates wrong number of nodes 

### ISSUE THREAD

**Issue by suleymanakbas91** [kyma-incubator/hydroform#87]
**Description**

When I specify the node count from CLI (`kyma provision gardener --target-provider azure --nodes 3`), hydroform creates 3 workers, which results in 6 nodes.

![Screenshot 2020-02-17 at 15 26 49](https://user-images.githubusercontent.com/5543238/74662324-02158680-519a-11ea-8660-f4b34ee57bab.png)

When I create a cluster through Gardener UI, it creates 1 worker with 3 nodes. 

![Screenshot 2020-02-17 at 15 26 59](https://user-images.githubusercontent.com/5543238/74662312-f924b500-5199-11ea-9133-642420226b67.png)

**Comment by rakesh-garimella** [comment]
@a-thaler  Should we rename nodes to `worker-group` or `auto-scaling-group` and pass 1 as default or should we use the node count passed here to be the minimum number of nodes in worker-group and max can be passed by the user and have always 1 `worker-group` or `auto-scaling-group`

**Comment by rakesh-garimella** [comment]
From Cli pass 
* min 2 and throw error  if less than 2 is passed for min
* max 3 default
* max = nodes

In Hydroform
* 1 worker group (remove loop)

**Comment by a-thaler** [comment]
I aligned with @rakesh-garimella by mainly comparing it with a GKE provisioning and thinking about what a user will expect. When creating a GKE cluster using the CLI there will be one default node pool created with specified machine type and an amount of "nodes" nodes.  The autoscaler will work with that nodes only. There is no way at the moment to specify a second node pool with different machine types.
In gardener it should be similar to have it consistent. There will be one worker group created using the specified machine and volume type. "nodes" should be the maximum nodes.

In future we should support multiple node pools/worker groups in general for all providers.
